switch to pnpm and upgrade to nextjs 16

diff --git a/client/web-frontend/Dockerfile.dev b/client/web-frontend/Dockerfile.dev
--- a/client/web-frontend/Dockerfile.dev
+++ b/client/web-frontend/Dockerfile.dev
@@ -4,7 +4,12 @@ WORKDIR /app
 
 COPY package*.json ./
 
-RUN npm ci
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 COPY . .
 
